version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
  backend:
    build: ./golang
    restart: always
    environment:
      MYSQL_HOSTNAME: mysql
      DEBUG: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: /bin/isucholar
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    volumes:
      - ./:/webapp

  mysql:
    image: mysql
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucholar
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    ports:
      - "7001:8080"

volumes:
  mysql:
